#!/bin/bash

#USAGE: jodo wget https://google.com.cu

#@migulelespauljr, @javier.cabrales, @engel

USER=miguel.hinojosa
PASS=CoalBitminer
echo "PFSENSE"
export http_proxy=http://${USER}:${PASS}@10.0.100.191:3128/
export https_proxy=http://${USER}:${PASS}@10.0.100.191:3128/
export ftp_proxy=http://${USER}:${PASS}@10.0.100.191:3128/
export HTTP_PROXY=http://${USER}:${PASS}@10.0.100.191:3128/
export HTTPS_PROXY=http://${USER}:${PASS}@10.0.100.191:3128/
export FTP_PROXY=http://${USER}:${PASS}@10.0.100.191:3128/
$2 $3 $4 $5 $6 $7 $8
